"""Create PlatformSettings table

Revision ID: create_platform_settings
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'create_platform_settings'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=255), nullable=True),
    sa.Column('platform_description', sa.String(length=1000), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('transaction_fee_percent', sa.Float(), nullable=True),
    sa.Column('minimum_transaction', sa.Float(), nullable=True),
    sa.Column('maximum_transaction', sa.Float(), nullable=True),
    sa.Column('wave_fee_percent', sa.Float(), nullable=True),
    sa.Column('orange_money_fee_percent', sa.Float(), nullable=True),
    sa.Column('stripe_fee_percent', sa.Float(), nullable=True),
    sa.Column('minimum_deposit', sa.Float(), nullable=True),
    sa.Column('maximum_deposit', sa.Float(), nullable=True),
    sa.Column('minimum_withdrawal', sa.Float(), nullable=True),
    sa.Column('maximum_withdrawal', sa.Float(), nullable=True),
    sa.Column('withdrawal_processing_time_hours', sa.Integer(), nullable=True),
    sa.Column('notify_on_transaction', sa.Boolean(), nullable=True),
    sa.Column('notify_on_deposit', sa.Boolean(), nullable=True),
    sa.Column('notify_on_withdrawal', sa.Boolean(), nullable=True),
    sa.Column('notify_on_gift', sa.Boolean(), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('require_2fa', sa.Boolean(), nullable=True),
    sa.Column('max_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('password_min_length', sa.Integer(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.String(length=500), nullable=True),
    sa.Column('extra_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
