"""initial schema

Revision ID: ca6bb67fec33
Revises: 
Create Date: 2026-02-01 04:23:25.959058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca6bb67fec33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_logs', 'fees_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=False)
    op.alter_column('admin_logs', 'fees_currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_admin_logs_action'), 'admin_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_related_transaction_id'), 'admin_logs', ['related_transaction_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_related_user_id'), 'admin_logs', ['related_user_id'], unique=False)
    op.alter_column('banned_user_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('banned_user_messages', 'channel',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=True)
    op.alter_column('banned_user_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('banned_user_messages', 'responded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('banned_user_messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_banned_messages_status'), table_name='banned_user_messages')
    op.drop_index(op.f('idx_banned_messages_user'), table_name='banned_user_messages')
    op.create_index(op.f('ix_banned_user_messages_id'), 'banned_user_messages', ['id'], unique=False)
    op.alter_column('bom_assets', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bom_assets', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'base_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bom_assets', 'current_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bom_assets', 'social_value',
               existing_type=sa.NUMERIC(precision=30, scale=18),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'current_social_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bom_assets', 'total_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'market_capitalization',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'capitalization_units',
               existing_type=sa.NUMERIC(precision=30, scale=18),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'redistribution_pool',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'social_accumulator',
               existing_type=sa.NUMERIC(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'palier_threshold',
               existing_type=sa.NUMERIC(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'palier_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'applied_micro_value',
               existing_type=sa.NUMERIC(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'treasury_pool',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'share_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'share_count_24h',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'interaction_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_buys',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_sells',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_volume_24h',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'trade_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_count_24h',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_count_24h',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'social_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'unique_holders_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'gift_acceptance_rate',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_shares',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_gifts_sent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_gifts_accepted',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'daily_interaction_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'social_value_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'interaction_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'price_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'edition_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'current_edition',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'price_change_24h',
               existing_type=sa.NUMERIC(precision=7, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'price_change_7d',
               existing_type=sa.NUMERIC(precision=7, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'volatility_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               server_default=None,
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_spread',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               server_default=None,
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_spread',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               server_default=None,
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_volume_24h',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_volume_24h',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'liquidity_pool',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_fees_collected',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'is_minted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'is_tradable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'royalty_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'minted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'nft_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'contract_address',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bom_assets', 'market_listed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint(op.f('bom_assets_token_id_key'), 'bom_assets', type_='unique')
    op.drop_index(op.f('idx_bom_assets_collection_id'), table_name='bom_assets')
    op.drop_index(op.f('idx_bom_assets_creator_id'), table_name='bom_assets')
    op.drop_index(op.f('idx_bom_assets_edition_type'), table_name='bom_assets')
    op.drop_index(op.f('idx_bom_assets_is_minted'), table_name='bom_assets')
    op.drop_index(op.f('idx_bom_assets_owner_id'), table_name='bom_assets')
    op.drop_index(op.f('idx_bom_assets_token_id'), table_name='bom_assets')
    op.create_index(op.f('ix_bom_assets_token_id'), 'bom_assets', ['token_id'], unique=True)
    op.drop_column('bom_assets', 'media_url')
    op.drop_column('bom_assets', 'base_value')
    op.alter_column('gift_transactions', 'fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('gift_transactions', 'wallet_transaction_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('nft_collections', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('nft_collections', 'total_items',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('nft_collections', 'total_volume',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('nft_collections', 'total_social_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('nft_collections', 'average_social_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('nft_collections', 'collection_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_nft_collections_id'), 'nft_collections', ['id'], unique=False)
    op.alter_column('platform_treasury', 'total_fees_collected',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               server_default=None,
               nullable=False)
    op.alter_column('platform_treasury', 'total_transactions',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.add_column('support_messages', sa.Column('thread_id', sa.Integer(), nullable=False))
    op.add_column('support_messages', sa.Column('sender_type', sa.Enum('USER', 'ADMIN', 'SYSTEM', name='supportsendertype'), nullable=False))
    op.add_column('support_messages', sa.Column('body', sa.Text(), nullable=False))
    op.add_column('support_messages', sa.Column('is_internal', sa.Boolean(), nullable=True))
    op.add_column('support_messages', sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('support_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('support_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('support_messages', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('support_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_messages_sender'), table_name='support_messages')
    op.drop_index(op.f('idx_messages_ticket'), table_name='support_messages')
    op.create_index(op.f('ix_support_messages_id'), 'support_messages', ['id'], unique=False)
    op.create_index(op.f('ix_support_messages_thread_id'), 'support_messages', ['thread_id'], unique=False)
    op.drop_constraint(op.f('support_messages_ticket_id_fkey'), 'support_messages', type_='foreignkey')
    op.create_foreign_key(None, 'support_messages', 'support_threads', ['thread_id'], ['id'])
    op.drop_column('support_messages', 'message')
    op.drop_column('support_messages', 'read_at')
    op.drop_column('support_messages', 'ticket_id')
    op.drop_column('support_messages', 'is_admin_response')
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('support_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('support_tickets', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('support_tickets', 'closed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('support_tickets', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_tickets_assigned'), table_name='support_tickets')
    op.drop_index(op.f('idx_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('idx_tickets_user'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.drop_constraint(op.f('support_tickets_user_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'users', ['user_id'], ['id'])
    op.execute(sa.text("UPDATE transactions SET type = 'legacy' WHERE type IS NULL"))
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'transaction_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('transactions_reference_key'), 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.alter_column('user_boms', 'profit_loss',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'fees_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'hold_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'times_shared',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'times_received_as_gift',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'total_trades',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'is_listed_for_trade',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'is_tradable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_boms', 'is_sold',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_user_boms_receiver_id'), table_name='user_boms')
    op.drop_index(op.f('idx_user_boms_sender_id'), table_name='user_boms')
    op.drop_index(op.f('idx_user_boms_transfer_id'), table_name='user_boms')
    op.drop_index(op.f('idx_user_boms_user_id_bom_id'), table_name='user_boms')
    op.drop_constraint(op.f('user_boms_transfer_id_key'), 'user_boms', type_='unique')
    op.create_index(op.f('ix_user_boms_transfer_id'), 'user_boms', ['transfer_id'], unique=True)
    op.create_foreign_key(None, 'user_boms', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'user_boms', 'users', ['user_id'], ['id'])
    op.alter_column('user_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('deposit', 'withdrawal', 'purchase', 'transfer', 'refund', 'royalties', 'bonus', 'correction', 'other_redistribution', 'nft_purchase', 'boom_purchase', 'boom_sell', 'gift_fee', 'commission', name='transactiontype'),
               existing_nullable=False,
               postgresql_using="transaction_type::transactiontype")
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    bind = op.get_bind()
    userstatus_new = postgresql.ENUM('active', 'review', 'limited', 'suspended', 'banned', name='userstatus_new')
    userstatus_new.create(bind, checkfirst=True)
    op.execute("ALTER TABLE users ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE userstatus_new USING lower(status::text)::userstatus_new")
    op.execute("ALTER TYPE userstatus RENAME TO userstatus_old")
    op.execute("ALTER TYPE userstatus_new RENAME TO userstatus")
    op.execute("DROP TYPE userstatus_old")
    op.execute(sa.text("UPDATE users SET status = 'active' WHERE status IS NULL"))
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('active', 'review', 'limited', 'suspended', 'banned', name='userstatus'),
               server_default='active',
               nullable=False)
    op.alter_column('users', 'status_source',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'status_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'suspended_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'suspension_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'last_suspension_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'banned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'banned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'last_suspension_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'suspension_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('users', 'suspended_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'status_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('users', 'status_source',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'manual'::character varying"),
               existing_nullable=True)
    bind = op.get_bind()
    userstatus_old = postgresql.ENUM('ACTIVE', 'REVIEW', 'LIMITED', 'SUSPENDED', 'BANNED', name='userstatus_old')
    userstatus_old.create(bind, checkfirst=True)
    op.execute("ALTER TABLE users ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE userstatus_old USING upper(status::text)::userstatus_old")
    op.execute("ALTER TYPE userstatus RENAME TO userstatus_new")
    op.execute("ALTER TYPE userstatus_old RENAME TO userstatus")
    op.execute("DROP TYPE userstatus_new")
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'REVIEW', 'LIMITED', 'SUSPENDED', 'BANNED', name='userstatus'),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_transactions', 'transaction_type',
               existing_type=sa.Enum('deposit', 'withdrawal', 'purchase', 'transfer', 'refund', 'royalties', 'bonus', 'correction', 'other_redistribution', 'nft_purchase', 'boom_purchase', 'boom_sell', 'gift_fee', 'commission', name='transactiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'user_boms', type_='foreignkey')
    op.drop_constraint(None, 'user_boms', type_='foreignkey')
    op.drop_index(op.f('ix_user_boms_transfer_id'), table_name='user_boms')
    op.create_unique_constraint(op.f('user_boms_transfer_id_key'), 'user_boms', ['transfer_id'])
    op.create_index(op.f('idx_user_boms_user_id_bom_id'), 'user_boms', ['user_id', 'bom_id'], unique=False)
    op.create_index(op.f('idx_user_boms_transfer_id'), 'user_boms', ['transfer_id'], unique=False)
    op.create_index(op.f('idx_user_boms_sender_id'), 'user_boms', ['sender_id'], unique=False)
    op.create_index(op.f('idx_user_boms_receiver_id'), 'user_boms', ['receiver_id'], unique=False)
    op.alter_column('user_boms', 'is_sold',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_boms', 'is_tradable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('user_boms', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_boms', 'is_listed_for_trade',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_boms', 'total_trades',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_boms', 'times_received_as_gift',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_boms', 'times_shared',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_boms', 'hold_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_boms', 'fees_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('user_boms', 'profit_loss',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.create_unique_constraint(op.f('transactions_reference_key'), 'transactions', ['reference'])
    op.alter_column('transactions', 'transaction_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_user_id_fkey'), 'support_tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.create_index(op.f('idx_tickets_user'), 'support_tickets', ['user_id'], unique=False)
    op.create_index(op.f('idx_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('idx_tickets_assigned'), 'support_tickets', ['assigned_to'], unique=False)
    op.alter_column('support_tickets', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('support_tickets', 'closed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('support_tickets', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('support_tickets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('support_tickets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=True)
    op.alter_column('support_tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'normal'::character varying"),
               existing_nullable=True)
    op.add_column('support_messages', sa.Column('is_admin_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('support_messages', sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('support_messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'support_messages', type_='foreignkey')
    op.create_foreign_key(op.f('support_messages_ticket_id_fkey'), 'support_messages', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_support_messages_thread_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_id'), table_name='support_messages')
    op.create_index(op.f('idx_messages_ticket'), 'support_messages', ['ticket_id'], unique=False)
    op.create_index(op.f('idx_messages_sender'), 'support_messages', ['sender_id'], unique=False)
    op.alter_column('support_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('support_messages', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('support_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('support_messages', 'updated_at')
    op.drop_column('support_messages', 'context_snapshot')
    op.drop_column('support_messages', 'is_internal')
    op.drop_column('support_messages', 'body')
    op.drop_column('support_messages', 'sender_type')
    op.drop_column('support_messages', 'thread_id')
    op.alter_column('platform_treasury', 'total_transactions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('platform_treasury', 'total_fees_collected',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               server_default=sa.text('0.00'),
               nullable=True)
    op.drop_index(op.f('ix_nft_collections_id'), table_name='nft_collections')
    op.alter_column('nft_collections', 'collection_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('nft_collections', 'average_social_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=sa.text('1.000'),
               existing_nullable=True)
    op.alter_column('nft_collections', 'total_social_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('nft_collections', 'total_volume',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('nft_collections', 'total_items',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('nft_collections', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('gift_transactions', 'wallet_transaction_ids',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('gift_transactions', 'fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.add_column('bom_assets', sa.Column('base_value', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('bom_assets', sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bom_assets_token_id'), table_name='bom_assets')
    op.create_index(op.f('idx_bom_assets_token_id'), 'bom_assets', ['token_id'], unique=False)
    op.create_index(op.f('idx_bom_assets_owner_id'), 'bom_assets', ['owner_id'], unique=False)
    op.create_index(op.f('idx_bom_assets_is_minted'), 'bom_assets', ['is_minted'], unique=False)
    op.create_index(op.f('idx_bom_assets_edition_type'), 'bom_assets', ['edition_type'], unique=False)
    op.create_index(op.f('idx_bom_assets_creator_id'), 'bom_assets', ['creator_id'], unique=False)
    op.create_index(op.f('idx_bom_assets_collection_id'), 'bom_assets', ['collection_id'], unique=False)
    op.create_unique_constraint(op.f('bom_assets_token_id_key'), 'bom_assets', ['token_id'])
    op.alter_column('bom_assets', 'market_listed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'contract_address',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'BOOMS_NFT_CONTRACT'::character varying"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'nft_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'minted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'royalty_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('10.0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'is_tradable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'is_minted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_fees_collected',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'liquidity_pool',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_volume_24h',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_volume_24h',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_spread',
               existing_type=sa.Numeric(precision=5, scale=3),
               server_default=sa.text('0.02'),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_spread',
               existing_type=sa.Numeric(precision=5, scale=3),
               server_default=sa.text('0.02'),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('bom_assets', 'volatility_score',
               existing_type=sa.Numeric(precision=5, scale=3),
               server_default=sa.text('0.01'),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('bom_assets', 'price_change_7d',
               existing_type=sa.NUMERIC(precision=7, scale=3),
               server_default=sa.text('0.000'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'price_change_24h',
               existing_type=sa.NUMERIC(precision=7, scale=3),
               server_default=sa.text('0.000'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'current_edition',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'edition_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'common'::character varying"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'price_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'interaction_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'social_value_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'daily_interaction_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=sa.text('1.000'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_gifts_accepted',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_gifts_sent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_shares',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'gift_acceptance_rate',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=sa.text('1.000'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'unique_holders_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'social_score',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               server_default=sa.text('1.000'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_count_24h',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_count_24h',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'trade_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_volume_24h',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_sells',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_buys',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'interaction_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'share_count_24h',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'share_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'sell_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'buy_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'treasury_pool',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'applied_micro_value',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'palier_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'palier_threshold',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'social_accumulator',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'redistribution_pool',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'capitalization_units',
               existing_type=sa.NUMERIC(precision=30, scale=18),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'market_capitalization',
               existing_type=sa.NUMERIC(precision=20, scale=4),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'total_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'current_social_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('bom_assets', 'social_value',
               existing_type=sa.NUMERIC(precision=30, scale=18),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('bom_assets', 'current_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('bom_assets', 'base_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('bom_assets', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=True)
    op.alter_column('bom_assets', 'token_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_banned_user_messages_id'), table_name='banned_user_messages')
    op.create_index(op.f('idx_banned_messages_user'), 'banned_user_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_banned_messages_status'), 'banned_user_messages', ['status'], unique=False)
    op.alter_column('banned_user_messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('banned_user_messages', 'responded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('banned_user_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('banned_user_messages', 'channel',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'app'::character varying"),
               existing_nullable=True)
    op.alter_column('banned_user_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_admin_logs_related_user_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_related_transaction_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action'), table_name='admin_logs')
    op.alter_column('admin_logs', 'fees_currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'FCFA'::character varying"),
               nullable=True)
    op.alter_column('admin_logs', 'fees_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               nullable=True)
    # ### end Alembic commands ###
